Import('env')

srcFiles = [
           'GenerateFunction.cpp',
           'CombineFunction.cpp',
           'DataPoint.cpp',
           'InputData.cpp',
           'GraphNode.cpp',
           'Graph.cpp',
           'GraphCompute.cpp',
           'GraphAlgorithmFactory.cpp',
           'main.cpp',
           ]

env.Program(target = 'GraphWorks', source = srcFiles)
