Import('env')

srcFiles = [
           'InputData.cpp',
           'GraphNode.cpp',
           'Graph.cpp',
           'GraphCompute.cpp',
           'GraphAlgorithmFactory.cpp',
           'main.cpp',
           ]

env.Program(target = 'GraphWorks', source = srcFiles)
